language: node_js
sudo: false

install:
  - curl -L https://static.rust-lang.org/rustup.sh | sh -s -- --yes --prefix=$PWD --disable-sudo --disable-ldconfig
  - export PATH=$PATH:$PWD/bin
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib

script:
  - rustc --version
  - make
  - make test
  - make book

notifications:
  email:
    - mdinger.bugzilla@gmail.com

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

branches:
  only: master

env:
  global:
    - secure: "oFD/tic8JAwpMXuMDBZXV4ot6w1NLWvHQTrDKmUHSMQJC1cbbrR1p5q8XayfjtmdqQdFQmIfM6YHEKeHw//ypgObWjYS8q00OaaMDXPTdmgr1Ee4nhgkkDihT+kVij0rn96W/QvyAVoaV5hJoyUr3Nhk+mnHEYm3M+Q3LAQglRg="
