language: node_js

before_install:
  - sudo add-apt-repository --yes ppa:hansjorg/rust
  - sudo apt-get update -qq

install:
  - npm install gitbook -g
  - sudo apt-get install -qq rust-nightly

script:
  - rustc --version
  - make
  - make test

branches:
  only: master
