language: node_js

install:
  - npm install gitbook -g
  - curl -s https://static.rust-lang.org/rustup.sh | sudo sh

script:
  - rustc --version
  - make
  - make test

after_success: bash deploy.sh

branches:
  only: master

secure: "oFD/tic8JAwpMXuMDBZXV4ot6w1NLWvHQTrDKmUHSMQJC1cbbrR1p5q8XayfjtmdqQdFQmIfM6YHEKeHw//ypgObWjYS8q00OaaMDXPTdmgr1Ee4nhgkkDihT+kVij0rn96W/QvyAVoaV5hJoyUr3Nhk+mnHEYm3M+Q3LAQglRg="
